name: Label PR 

on:
  pull_request:
    types: [ edited ]
  workflow_dispatch: # Allows manual triggering of the workflow


jobs:
  checker:
    uses: WeyeTech/github-actions/.github/workflows/label-pr-actions.yaml@master
    with:
      pr_title: ${{ github.event.pull_request.title }}
    secrets: inherit