name: Validate PR Label

on:
  pull_request:
    types: [ edited , labeled, unlabeled ]

jobs:
  checker:
    uses: WeyeTech/github-actions/.github/workflows/pr-label-checker-actions.yaml@master
    with:
      pr_title: ${{ github.event.pull_request.title }}
    secrets: inherit